name: Deploy Code Changes to Developmental Site
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy testing
        env:
          FIREBASE_TOKEN: "1//05GK37eiEfUsUCgYIARAAGAUSNwF-L9Irbuwe8qn1kzgBqdDkfUK-pmuivRnkbbqF-3ZHOujkX0uiyC0yFdk4ZjmqjyGoVXYpvQY"
